# These are supported funding model platforms

github: farhnkrnapratma
patreon: farhnkrnapratma
open_collective: farhnkrnapratma
buy_me_a_coffee: farhnkrnapratma
ko_fi: farhnkrnapratma
custom: ['paypal.me/farhnkrnapratma']
